name: pollen_id
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pandas=1.4.4
  - numpy=1.21.5
  - matplotlib=3.5.2
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - tqdm=4.64.0
  - pillow=9.0.1
  - torchmetrics=0.9.3
  - seaborn=0.11.2
  - flask=2.1.3
  - flask-cors=3.0.10
  - simplejson=3.17.6
  - pip:
    - opencv-contrib-python==4.6.0.66
prefix: /Users/kavidey/.pyenv/versions/anaconda3-2022.05/envs/pollen_id
